// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TopoCentras.Data;

#nullable disable

namespace TopoCentras.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208123247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TopoCentras.Core.Models.Klientas", b =>
                {
                    b.Property<Guid>("KlientasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("KlientasId");

                    b.ToTable("Klientai");
                });

            modelBuilder.Entity("TopoCentras.Core.Models.Preke", b =>
                {
                    b.Property<Guid>("PrekeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Gamintojas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Kaina")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("PrekeId");

                    b.ToTable("Prekes");
                });

            modelBuilder.Entity("TopoCentras.Core.Models.Uzsakymas", b =>
                {
                    b.Property<Guid>("UzsakymasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("BendraUzsakymoSuma")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("KlientasId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UzsakymoSukurimoData")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UzsakymasId");

                    b.HasIndex("KlientasId");

                    b.ToTable("Uzsakymai");
                });

            modelBuilder.Entity("TopoCentras.Core.Models.UzsakymasPreke", b =>
                {
                    b.Property<Guid>("UzsakymasId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PrekeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Kiekis")
                        .HasColumnType("int");

                    b.HasKey("UzsakymasId", "PrekeId");

                    b.HasIndex("PrekeId");

                    b.ToTable("UzsakymoPrekes");
                });

            modelBuilder.Entity("TopoCentras.Core.Models.Uzsakymas", b =>
                {
                    b.HasOne("TopoCentras.Core.Models.Klientas", "Klientas")
                        .WithMany()
                        .HasForeignKey("KlientasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klientas");
                });

            modelBuilder.Entity("TopoCentras.Core.Models.UzsakymasPreke", b =>
                {
                    b.HasOne("TopoCentras.Core.Models.Preke", "Preke")
                        .WithMany()
                        .HasForeignKey("PrekeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TopoCentras.Core.Models.Uzsakymas", "Uzsakymas")
                        .WithMany("UzsakymasPrekes")
                        .HasForeignKey("UzsakymasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preke");

                    b.Navigation("Uzsakymas");
                });

            modelBuilder.Entity("TopoCentras.Core.Models.Uzsakymas", b =>
                {
                    b.Navigation("UzsakymasPrekes");
                });
#pragma warning restore 612, 618
        }
    }
}
